version: '3.8'

services:
  backend:
    build: ./backend/crypto_project
    ports:
      - "5000:5000"
    volumes:
      - ./backend/crypto_project:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - app-network

  frontend:
    build: ./rental-query-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    networks:
      - app-network

  db:
    build: ./database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data between restarts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: